// Writes docs/COVERAGE.md: every stop by line and level, and what is deliberately not covered.
// Run: node scripts/coverage.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const lines = read('content/lines.json');
const order = read('content/order.json');
const stops = order.map((id, i) => ({ ...read(`content/stops/${id}.json`), n: i + 1 }));
const LV = ['beginner', 'intermediate', 'advanced'];
const cap = (s) => s[0].toUpperCase() + s.slice(1);

let md = `# Coverage map\n\nGenerated by \`node scripts/coverage.mjs\`. ${stops.length} stops across ${lines.length} lines.\n\n`;
md += `Read across a row to go from basics to advanced inside one topic. Numbers are the stop's position on the map.\n\n`;
md += `| Line | ${LV.map(cap).join(' | ')} |\n|---|---|---|---|\n`;
lines.forEach((l, i) => {
  const cells = LV.map((k) => {
    const s = stops.filter((x) => x.line === i + 1 && x.level === k);
    return s.length ? s.map((x) => `${x.n}. ${x.shortTitle}`).join('<br>') : '-';
  });
  md += `| **${l.name}** | ${cells.join(' | ')} |\n`;
});
const totals = LV.map((k) => stops.filter((x) => x.level === k).length);
md += `| **Total** | ${totals.join(' | ')} |\n\n`;
md += `## What "complete" means here\n\nNo course can cover all of AI. This map aims to give a complete practical picture: someone who rides it from the first stop to the last will meet every major family of ideas used to build AI systems, in the order they are usually needed, and will know which approach fits which problem and what goes wrong when it is misused.\n\n`;
md += `## Deliberately left out or only touched on\n\n`;
md += `- Math foundations (excluded on purpose: every stop is explained in plain words).\n`;
md += `- Hands-on coding labs and notebooks. The stops teach choices and architecture, not code.\n`;
md += `- Graph neural networks and other graph machine learning.\n`;
md += `- Robotics and embodied AI.\n`;
md += `- Reinforcement learning beyond the practical ladder (tests, bandits, full RL).\n`;
md += `- Speech and audio beyond the vision and speech tasks stop.\n`;
md += `- Alignment and interpretability research. Practical safety is covered; research topics are not.\n`;
md += `- Energy and environmental cost of AI.\n`;
md += `- Detailed regional regulation. The privacy and governance stop lists questions to ask, not legal advice.\n`;
md += `- Certification mapping (for example, which stops help with a given vendor exam).\n\n`;
md += `Want one of these? See CONTRIBUTING.md.\n`;
fs.writeFileSync(path.join(root, 'docs', 'COVERAGE.md'), md);
console.log(`Wrote docs/COVERAGE.md (${stops.length} stops)`);
